### ISSUE TITLE
sp-tool install issue

### ISSUE THREAD

**Issue by designel** [mlasevich/sharepoint-tool#1]
Hello, 

i tried th tool install , but i still have the following error : 

'sp-tool' is not recognized as an internal or external command,
operable program or batch file.
I do the tool registration in my tenant SharePoint.. 

thank you in advance.
Regards.

**Comment by mlasevich** [comment]
If you are installing via PIP, chances are that your script installation directory is for some reason not in your PATH. You can add it to the path, but you would need to determine what it is and it is highly dependent on your setup. You may need to search your disk for the generated script or reinstall and look for a message about where it is installed like:

```
$  pip3 install --force-reinstall sharepoint-tool
...
 WARNING: The script sp-tool is installed in '.....' which is not on PATH.
 ```

If you still cannot find where it is installing the script, you can use a venv  and install there (in which case it will be inside venv's `bin` directory) or just call the module directly - `python3 -m sp_tool.tool  <args>`


To use venv do something like:
```
$ python3 -m venv myVenv
$ source ./myVenv/bin/activate
(myVenv) $ pip install sharepoint-tool
(myVenv) $ sp-tool <args>
```
(you can then call it directly from ./myVenv/bin/)

**Comment by designel** [comment]
hello , 

sorry again to disturb you, i tried all of solution prposed : for reinstall i have the following error : 

pip3 install --force-reinstall sharepoint-tool
Collecting sharepoint-tool
  Using cached sharepoint_tool-1.0.0-py3-none-any.whl (22 kB)
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting click
  Using cached click-8.0.3-py3-none-any.whl (97 kB)
Collecting PyYaml
  Using cached PyYAML-6.0-cp39-cp39-win_amd64.whl (151 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Installing collected packages: urllib3, idna, colorama, charset-normalizer, certifi, requests, PyYaml, click, sharepoint-tool
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.7
    Uninstalling urllib3-1.26.7:
      Successfully uninstalled urllib3-1.26.7
  Attempting uninstall: idna
    Found existing installation: idna 3.3
    Uninstalling idna-3.3:
      Successfully uninstalled idna-3.3
  Attempting uninstall: colorama
    Found existing installation: colorama 0.4.4
    Uninstalling colorama-0.4.4:
      Successfully uninstalled colorama-0.4.4
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 2.0.7
    Uninstalling charset-normalizer-2.0.7:
      Successfully uninstalled charset-normalizer-2.0.7
  WARNING: Failed to write executable - trying to use .deleteme logic
  Rolling back uninstall of charset-normalizer
  Moving to c:\python39\lib\site-packages\charset_normalizer-2.0.7.dist-info\
   from C:\Python39\Lib\site-packages\~harset_normalizer-2.0.7.dist-info
  Moving to c:\python39\lib\site-packages\charset_normalizer\
   from C:\Python39\Lib\site-packages\~harset_normalizer
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'c:\\python39\\Scripts\\normalizer.exe' -> 'c:\\python39\\Scripts\\normalizer.exe.deleteme'

i tried to define a venv i have the following issue : 

Traceback (most recent call last):
  File "C:\Python39\Lib\site-packages\sp_tool.py", line 13, in <module>
    from .logging import LOG
ImportError: attempted relative import with no known parent package


thank you in advance,

**Comment by mlasevich** [comment]
Seems like some windows oddity. I can remove the thing causing the immediate issue, lets see if that fixes it for you

**Comment by mlasevich** [comment]
I am publishing v1.0.1 with relative imports removed to avoid this issue. I do not have a windows box handy to test, please test and let me know if it installs

**Comment by designel** [comment]
still have same error :( : 

Traceback (most recent call last):
  File "C:\Python39\Lib\site-packages\sp_tool.py", line 13, in <module>
    from .logging import LOG
ImportError: attempted relative import with no known parent package


 WARNING: Failed to write executable - trying to use .deleteme logic
  Rolling back uninstall of charset-normalizer
  Moving to c:\python39\lib\site-packages\charset_normalizer-2.0.7.dist-info\
   from C:\Python39\Lib\site-packages\~harset_normalizer-2.0.7.dist-info
  Moving to c:\python39\lib\site-packages\charset_normalizer\
   from C:\Python39\Lib\site-packages\~harset_normalizer
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'c:\\python39\\Scripts\\normalizer.exe' -> 'c:\\python39\\Scripts\\normalizer.exe.deleteme'

**Comment by mlasevich** [comment]
Are you sure you are installing version 1.0.1? That error references a line from 1.0.0, but it has been altered in 1.0.1

**Comment by designel** [comment]
Hello again, 

yes, i m sure i juste reinstall all package : 

Collecting sharepoint-tool
  Using cached sharepoint_tool-1.0.1-py3-none-any.whl (22 kB)
Requirement already satisfied: requests in c:\python39\lib\site-packages (from sharepoint-tool) (2.26.0)
Requirement already satisfied: click in c:\python39\lib\site-packages (from sharepoint-tool) (8.0.1)
Requirement already satisfied: PyYaml in c:\python39\lib\site-packages (from sharepoint-tool) (5.4.1)
Requirement already satisfied: colorama in c:\python39\lib\site-packages (from click->sharepoint-tool) (0.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\python39\lib\site-packages (from requests->sharepoint-tool) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\python39\lib\site-packages (from requests->sharepoint-tool) (2021.5.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python39\lib\site-packages (from requests->sharepoint-tool) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\python39\lib\site-packages (from requests->sharepoint-tool) (2.0.7)
Installing collected packages: sharepoint-tool
  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'c:\\python39\\Scripts\\sp-tool.exe' -> 'c:\\python39\\Scripts\\sp-tool.exe.deleteme'

thank you ,

**Comment by mlasevich** [comment]
Ahh, so not exactly same (or rather partly the same). I was focusing on the first error, that is gone, but the other error is unrelated.  a quick Google says that last error with '.deleteme' comes from not having rights and that you should try this as an administrator. Try that.

**Comment by designel** [comment]
i m the admin of my machine , so i will retry to edit  some settings and retry again.

**Comment by mlasevich** [comment]
IIRC, in windows "being admin" and "running as admin" are separate things, open your terminal/shell with "as admin" setting - you need to right click and select "run as administrator" or something like that

**Comment by mlasevich** [comment]
Also, from what I understand, the error appears to only affect the binary creation but the module is installed, so you should be able to also run it without the binary as a python module via `python3 -m sp_tool ...` command

**Comment by designel** [comment]
thank you so much , my install is ok now 
the module was  installed but was blocked by our entreprise policies so  now i m able to show the application lib.

**Comment by mlasevich** [comment]
closing
